name: JavaScript Website Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Run client tests
        run: |
          cd client
          npm test

      - name: Run server tests
        run: |
          cd server
          npm test

  deploy-client:
    name: Deploy Client
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy client to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.CLIENT_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  deploy-server:
    name: Deploy Server
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy server to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}