name: JavaScript Website Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Run client tests
        run: |
          cd client
          npm test

      - name: Run server tests
        run: |
          cd server
          npm test
#  deploy:
#    need: test